from .api_tokens_management import (
    CreateApiTokenRequestDto,
    CreateApiTokenResponseDto,
    DeleteApiTokenResponseDto,
    FindAllApiTokensResponseDto,
    GetApiTokenScopesResponseDto,
)
from .auth import (
    GetPasskeyAuthenticationOptionsResponseDto,
    GetStatusResponseDto,
    LoginRequestDto,
    LoginResponseDto,
    LoginTelegramRequestDto,  # Legacy alias
    OAuth2AuthorizeRequestDto,
    OAuth2AuthorizeResponseDto,
    OAuth2CallbackRequestDto,
    OAuth2CallbackResponseDto,
    RegisterRequestDto,
    RegisterResponseDto,
    StatusResponseDto,  # Legacy alias
    TelegramCallbackRequestDto,
    TelegramCallbackResponseDto,
    VerifyPasskeyAuthenticationRequestDto,
    VerifyPasskeyAuthenticationResponseDto,
)
from .bandwidthstats import (
    GetInternalSquadUserUsageResponseDto,
    GetNodesRealtimeUsageResponseDto,
    GetNodesUsageByRangeResponseDto,
    GetNodesUsageRequestDto,
    GetNodesUsageResponseDto,
    GetStatsNodesRealtimeUsageResponseDto,
    GetStatsNodesUsageResponseDto,
    GetStatsNodesUsersUsageRequestDto,
    GetStatsNodesUsersUsageResponseDto,
    GetStatsNodeUsersUsageResponseDto,
    GetStatsUserUsageResponseDto,
    GetUserUsageByRangeResponseDto,
    # Data Models
    NodeRealtimeUsageItem,
    NodeRealtimeUsageResponseDto,
    NodeSeriesItem,
    NodesRealtimeUsageResponseDto,  # Legacy alias
    NodesUsageResponseDto,  # Legacy alias
    NodeUsageEntry,
    NodeUsageResponseDto,
    NodeUsageUser,
    SquadUserUsageDay,
    SquadUserUsageNode,
    StatsNodesUsageData,
    StatsNodeUsersUsageData,
    StatsUserUsageData,
    TopNodeItem,
    TopUserItem,
)
from .config_profiles import (
    ConfigProfileDto,
    CreateConfigProfileRequestDto,
    CreateConfigProfileResponseDto,
    DeleteConfigProfileResponseDto,
    GetAllConfigProfilesResponseDto,
    GetAllConfigProfilesResponsePaginated,
    GetConfigProfileByUuidResponseDto,
    GetInboundsByProfileUuidResponseDto,
    InboundDto,
    NodesProfileDto,
    ReorderConfigProfileItem,
    ReorderConfigProfilesRequestDto,
    ReorderConfigProfilesResponseDto,
    UpdateConfigProfileRequestDto,
    UpdateConfigProfileResponseDto,
)
from .config_profiles import (
    GetAllInboundsResponseDto as GetAllConfigProfileInboundsResponseDto,
)
from .external_squads import (
    AddUsersToExternalSquadResponseDto,
    CreateExternalSquadRequestDto,
    CreateExternalSquadResponseDto,
    DeleteExternalSquadResponseDto,
    ExternalSquadDto,
    ExternalSquadInfoDto,
    ExternalSquadSubscriptionSettingsDto,
    ExternalSquadTemplateDto,
    GetExternalSquadByUuidResponseDto,
    GetExternalSquadsResponseDto,
    RemoveUsersFromExternalSquadResponseDto,
    ReorderExternalSquadItem,
    ReorderExternalSquadsRequestDto,
    ReorderExternalSquadsResponseDto,
    TemplateType,
    UpdateExternalSquadRequestDto,
    UpdateExternalSquadResponseDto,
)
from .hosts import (
    CreateHostInboundData,
    CreateHostRequestDto,
    CreateHostResponseDto,
    DeleteHostResponseDto,
    GetAllHostsResponseDto,
    GetAllHostTagsResponseDto,
    GetOneHostResponseDto,
    HostInboundData,
    HostResponseDto,
    HostsResponseDto,  # Legacy alias
    ReorderHostItem,
    ReorderHostRequestDto,
    ReorderHostResponseDto,
    UpdateHostRequestDto,
    UpdateHostResponseDto,
)
from .hosts_bulk_actions import (
    BulkDeleteHostsResponseDto,
    BulkDisableHostsResponseDto,
    BulkEnableHostsResponseDto,
    UpdateManyHostsRequestDto,
    UpdateManyHostsResponseDto,
)
from .hwid import (
    CreateHWIDUser,  # Legacy alias
    CreateUserHwidDeviceRequestDto,
    CreateUserHwidDeviceResponseDto,
    DeleteUserAllHwidDeviceRequestDto,
    DeleteUserHwidDeviceRequestDto,
    DeleteUserHwidDeviceResponseDto,
    GetHwidStatisticsResponseDto,
    GetTopUsersByHwidDevicesResponseDto,
    GetUserHwidDevicesResponseDto,
    HWIDDeleteRequest,  # Legacy alias
    HWIDUserResponseDto,  # Legacy alias
    HWIDUserResponseDtoList,  # Legacy alias
    TopUserByHwidDevicesDto,
    TopUsersByHwidDevicesData,
)
from .inbounds import (
    AllInboundsData,
    FullInboundResponseDto,
    FullInboundsResponseDto,
    FullInboundStatistic,
    GetAllInboundsResponseDto,
    GetFullInboundsResponseDto,
    GetInboundsByProfileUuidResponseDto,
    GetInboundsResponseDto,
    InboundResponseDto,
    InboundsByProfileData,
    InboundsResponseDto,  # Legacy alias
)
from .infra_billing import (
    CreateInfraBillingHistoryRecordRequestDto,
    CreateInfraBillingHistoryRecordResponseDto,
    CreateInfraBillingNodeRequestDto,
    CreateInfraBillingNodeResponseDto,
    CreateInfraProviderRequestDto,
    CreateInfraProviderResponseDto,
    DeleteInfraBillingHistoryRecordByUuidResponseDto,
    DeleteInfraBillingNodeByUuidResponseDto,  # ПЕРЕИМЕНОВАНА (было DeleteInfraBillingNodeResponseDto)
    DeleteInfraBillingNodeResponseDto,  # LEGACY
    DeleteInfraProviderByUuidResponseDto,  # ПЕРЕИМЕНОВАНА (было DeleteInfraProviderResponseDto)
    DeleteInfraProviderResponseDto,  # LEGACY
    GetAllInfraBillingHistoryResponseDto,  # LEGACY
    GetAllInfraBillingNodesResponseDto,  # LEGACY
    GetAllInfraProvidersResponseDto,  # LEGACY
    GetInfraBillingHistoryByUuidResponseDto,
    GetInfraBillingHistoryRecordsResponseDto,  # ПЕРЕИМЕНОВАНА (было GetAllInfraBillingHistoryResponseDto)
    GetInfraBillingNodeByUuidResponseDto,
    GetInfraBillingNodesResponseDto,  # ПЕРЕИМЕНОВАНА (было GetAllInfraBillingNodesResponseDto)
    GetInfraProviderByUuidResponseDto,
    GetInfraProvidersResponseDto,  # ПЕРЕИМЕНОВАНА (было GetAllInfraProvidersResponseDto)
    InfraBillingHistoryDto,
    InfraBillingNodeDto,
    InfraProviderDto,
    NodeDto,
    UpdateInfraBillingNodeRequestDto,
    UpdateInfraBillingNodeResponseDto,
    UpdateInfraProviderRequestDto,
    UpdateInfraProviderResponseDto,
)
from .internal_squads import (
    AddManyUsersToInternalSquadRequestDto,
    AddManyUsersToInternalSquadResponseDto,
    AddUsersToInternalSquadRequestDto,
    AddUsersToInternalSquadResponseDto,
    CreateInternalSquadRequestDto,
    CreateInternalSquadResponseDto,
    DeleteInternalSquadResponseDto,
    DeleteManyUsersFromInternalSquadRequestDto,
    DeleteManyUsersFromInternalSquadResponseDto,
    DeleteUsersFromInternalSquadRequestDto,
    DeleteUsersFromInternalSquadResponseDto,
    GetAllInternalSquadsResponseDto,
    GetInternalSquadAccessibleNodesResponseDto,
    GetInternalSquadByUuidResponseDto,
    GetInternalSquadUsageResponseDto,
    InternalSquadDto,
    InternalSquadUsageUser,
    ReorderInternalSquadItem,
    ReorderInternalSquadsRequestDto,
    ReorderInternalSquadsResponseDto,
    UpdateInternalSquadRequestDto,
    UpdateInternalSquadResponseDto,
)
from .connections import (
    ConnectionIp,
    ConnectionsByNodeResponseDto,
    ConnectionsByNodeResult,
    ConnectionsByNodeResultResponseDto,
    ConnectionsByNodeUser,
    ConnectionsByUserNode,
    ConnectionsByUserResponseDto,
    ConnectionsByUserResult,
    ConnectionsByUserResultResponseDto,
    ConnectionsJobData,
    ConnectionsProgress,
    DropByIpAddresses,
    DropByUserIds,
    # Request DTOs
    DropConnectionsRequestDto,
    DropConnectionsResponseDto,
    TargetAllNodes,
    TargetSpecificNodes,
)
from .keygen import GetPubKeyResponseDto, PubKeyResponseDto  # Legacy alias
from .metadata import (
    GetMetadataResponseDto as MetadataResponseDto,
)
from .metadata import (
    GetNodeMetadataResponseDto,
    GetUserMetadataResponseDto,
    UpsertNodeMetadataRequestBodyDto,
    UpsertNodeMetadataResponseDto,
    UpsertUserMetadataRequestBodyDto,
    UpsertUserMetadataResponseDto,
)
from .node_plugins import (
    BlockIpItemDto,
    BlockIpsCommandDto,
    CloneNodePluginRequestDto,
    CloneNodePluginResponseDto,
    CreateNodePluginRequestDto,
    CreateNodePluginResponseDto,
    DeleteNodePluginResponseDto,
    GetNodePluginResponseDto,
    GetNodePluginsResponseDto,
    GetTorrentBlockerReportsResponseDto,
    GetTorrentBlockerReportsStatsResponseDto,
    NodePluginDto,
    PluginExecutorRequestDto,
    PluginExecutorResponseDto,
    RecreateTablesCommandDto,
    ReorderNodePluginItem,
    ReorderNodePluginsRequestDto,
    ReorderNodePluginsResponseDto,
    TargetAllNodesDto,
    TargetSpecificNodesDto,
    TorrentBlockerReportRecordDto,
    TruncateTorrentBlockerReportsResponseDto,
    UnblockIpsCommandDto,
    UpdateNodePluginRequestDto,
    UpdateNodePluginResponseDto,
)
from .nodes import (
    BulkNodesUpdateRequestDto,
    BulkNodesUpdateResponseDto,
    CreateNodeRequestDto,
    CreateNodeResponseDto,
    DeleteNodeResponseDto,
    DisableNodeResponseDto,
    EnableNodeResponseDto,
    ExcludedInbounds,
    GetAllNodesResponseDto,
    GetAllNodesTagsResponseDto,
    GetOneNodeResponseDto,
    NodeBulkActionType,
    NodeConfigProfileDto,
    NodeConfigProfileRequestDto,
    NodeResponseDto,
    NodesBulkActionsRequestDto,
    NodesBulkActionsResponseDto,
    NodesResponseDto,  # Legacy alias
    NodesUpdateFieldsDto,
    ProfileModificationRequestDto,
    ProfileModificationResponseDto,
    ReorderNodeRequestDto,
    ReorderNodeResponseDto,
    ResetNodeTrafficRequestDto,
    ResetNodeTrafficResponseDto,
    RestartAllNodesRequestBodyDto,
    RestartAllNodesRequestDto,  # Legacy alias,
    RestartNodeRequestBodyDto,
    RestartAllNodesResponseDto,
    RestartNodeResponseDto,
    UpdateNodeRequestDto,
    UpdateNodeResponseDto,
)
from .nodes_usage_history import (
    GetNodesUsageByRangeResponseDto,
    GetNodeUserUsageByRangeResponseDto,
    GetUserAccessibleNodesResponseDto,
    NodeInfoDto,
    NodeUsageDto,
    UserUsageDto,
)
from .passkeys import (
    DeletePasskeyRequestDto,
    DeletePasskeyResponseDto,
    GetAllPasskeysResponseDto,
    GetPasskeyRegistrationOptionsResponseDto,
    PasskeyDto,
    UpdatePasskeyRequestDto,
    UpdatePasskeyResponseDto,
    VerifyPasskeyRegistrationRequestDto,
    VerifyPasskeyRegistrationResponseDto,
)
from .remnawave_settings import (
    BrandingSettings,
    GenericOAuth2Settings,
    GetRemnawaveSettingsResponseDto,
    GitHubOAuth2Settings,
    KeycloakOAuth2Settings,
    OAuth2Settings,
    PasskeySettings,
    PasswordSettings,
    PocketIdOAuth2Settings,
    RemnawaveSettingsData,
    TelegramAuthSettings,
    UpdateRemnawaveSettingsRequestDto,
    UpdateRemnawaveSettingsResponseDto,
    YandexOAuth2Settings,
)
from .snippets import (
    CreateSnippetRequestDto,
    CreateSnippetResponseDto,
    DeleteSnippetRequestDto,
    DeleteSnippetResponseDto,
    GetSnippetsResponseDto,
    SnippetItem,
    SnippetsData,
    UpdateSnippetRequestDto,
    UpdateSnippetResponseDto,
)
from .subscription import (
    GetAllSubscriptionsResponseDto,
    GetConnectionKeysByUuidResponseDto,
    GetRawSubscriptionByShortUuidResponseDto,
    GetSubscriptionByShortUUIDResponseDto,
    GetSubscriptionByUserIdResponseDto,
    GetSubscriptionByUsernameResponseDto,
    GetSubscriptionInfoResponseDto,
    RawSettings,
    SubscriptionInfoResponseDto,  # Legacy alias
    UserSubscription,
)
from .subscription_page import (
    CloneSubscriptionPageConfigRequestDto,
    CloneSubscriptionPageConfigResponseDto,
    CreateSubscriptionPageConfigRequestDto,
    CreateSubscriptionPageConfigResponseDto,
    DeleteSubscriptionPageConfigResponseDto,
    GetSubpageConfigByShortUuidRequestBodyDto,
    GetSubpageConfigByShortUuidResponseDto,
    GetSubscriptionPageConfigResponseDto,
    GetSubscriptionPageConfigsResponseDto,
    ReorderSubscriptionPageConfigItem,
    ReorderSubscriptionPageConfigsRequestDto,
    ReorderSubscriptionPageConfigsResponseDto,
    SubpageConfigData,
    SubscriptionPageConfigDto,
    UpdateSubscriptionPageConfigRequestDto,
    UpdateSubscriptionPageConfigResponseDto,
)
from .subscription_request_history import (
    AppStatItem,
    GetAllSubscriptionRequestHistoryResponseDto,
    GetSubscriptionRequestHistoryStatsResponseDto,
    HourlyRequestStat,
    SubscriptionRequestHistoryData,
    SubscriptionRequestHistoryRecord,
    SubscriptionRequestHistoryStatsData,
)
from .subscriptions_settings import (
    # Backward compatibility aliases
    CustomRemarks,
    CustomRemarksDto,
    GetSubscriptionSettingsResponseDto,
    HwidSettings,
    HwidSettingsDto,
    ResponseModificationEncryption,
    ResponseModificationHeader,
    ResponseModifications,
    ResponseRule,
    ResponseRuleCondition,
    ResponseRules,
    ResponseRulesSettings,
    SubscriptionSettingsResponseDto,
    SubscriptionType,
    UpdateSubscriptionSettingsRequestDto,
    UpdateSubscriptionSettingsResponseDto,
)
from .subscriptions_template import (
    CreateSubscriptionTemplateRequestDto,
    CreateSubscriptionTemplateResponseDto,
    DeleteSubscriptionTemplateResponseDto,
    GetTemplateResponseDto,
    GetTemplatesResponseDto,
    ReorderSubscriptionTemplatesRequestDto,
    ReorderSubscriptionTemplatesResponseDto,
    ReorderTemplateItem,
    TemplateInfoDto,
    TemplateResponseDto,
    UpdateTemplateRequestDto,
    UpdateTemplateResponseDto,
)
from .system import (
    BandwidthStatistic,
    BandwidthStatisticResponseDto,
    ConfigurationMisc,
    ConfigurationNotifications,
    ConfigurationService,
    CPUStatistic,
    DebugSrrMatcherRequestDto,
    DebugSrrMatcherResponseDto,
    EncryptHappCryptoLinkRequestDto,
    EncryptHappCryptoLinkResponseDto,
    GetBandwidthStatsResponseDto,
    GetConfigurationResponseDto,
    GetHttpStatsResponseDto,
    GetMetadataResponseDto,
    GetNodesMetricsResponseDto,
    GetNodesStatisticsResponseDto,
    GetRecapResponseDto,
    GetRemnawaveHealthResponseDto,
    GetStatsDigestResponseDto,
    GetStatsResponseDto,
    GetX25519KeyPairResponseDto,
    HttpStatsRoute,
    MemoryStatistic,
    NodesStatisticResponseDto,
    NodeStatistic,
    OnlineStatistic,
    RecapThisMonth,
    RecapTotal,
    StatisticResponseDto,
    StatsDigestHwidDevices,
    StatsDigestTraffic,
    StatsDigestUsers,
    StatusCounts,
    UsersStatistic,
    X25519KeyPair,
)
from .users import (
    ActivateAllInboundsResponseDto,
    ActiveInternalSquadDto,
    # Request DTOs
    CreateUserRequestDto,
    # Response DTOs - Single User
    CreateUserResponseDto,
    # Other Response DTOs
    DeleteUserResponseDto,
    DisableUserResponseDto,
    EnableUserResponseDto,
    ExtendUserRequestDto,
    ExtendUserResponseDto,
    GetAllTagsResponseDto,
    # Response DTOs - Collections
    GetAllUsersResponseDto,
    GetUsersStreamResponseDto,
    # Alias
    GetSubscriptionRequestsResponseDto,
    GetUserByIdResponseDto,
    GetUserByShortUuidResponseDto,
    GetUserByUsernameResponseDto,
    GetUserSubscriptionRequestHistoryResponseDto,
    HappCrypto,
    ResetUserTrafficResponseDto,
    ResolveUserRequestBodyDto,
    ResolveUserResponseDto,
    RevokeUserRequestDto,
    RevokeUserSubscriptionResponseDto,
    SubscriptionRequestRecord,
    SubscriptionRequestsResponseData,
    TagsResponseDto,
    UpdateUserRequestDto,
    UpdateUserResponseDto,
    UserActiveInboundsDto,
    UserLastConnectedNodeDto,
    # Base DTOs
    UserResponseDto,
    UsersResponseDto,
    # Data DTOs
    UserTrafficDto,
)
from .users_bulk_actions import (
    BulkAllExtendExpirationDateRequestDto,
    BulkAllExtendExpirationDateResponseDto,
    BulkAllResetTrafficUsersResponseDto,
    BulkAllUpdateUsersRequestDto,
    BulkAllUpdateUsersResponseDto,
    BulkDeleteUsersByStatusRequestDto,
    BulkDeleteUsersByStatusResponseDto,
    BulkDeleteUsersRequestDto,
    BulkDeleteUsersResponseDto,
    BulkEventResponseData,
    BulkExtendExpirationDateRequestDto,
    BulkExtendExpirationDateResponseDto,
    BulkResetTrafficUsersRequestDto,
    BulkResetTrafficUsersResponseDto,
    BulkResponseData,
    BulkResponseDto,
    BulkRevokeUsersSubscriptionRequestDto,
    BulkRevokeUsersSubscriptionResponseDto,
    BulkUpdateUsersInternalSquadsRequestDto,
    BulkUpdateUsersRequestDto,
    BulkUpdateUsersResponseDto,
    BulkUpdateUsersSquadsRequestDto,
    BulkUpdateUsersSquadsResponseDto,
    TagStr,
    UpdateUserFields,
)
from .users_stats import UserUsageByRange, UserUsageByRangeResponseDto
from .webhook import (
    BaseUserDto,
    ConfigProfileInboundDto,
    CrmEventDto,
    CustomErrorEventDto,
    HwidUserDeviceDto,
    InfraProviderDto,
    InternalSquadDto,
    LastConnectedNodeDto,
    LoginAttemptDto,
    NodeDto,
    NodeEventDto,
    NodeSystemDto,
    NodeSystemInfoDto,
    NodeSystemInterfaceDto,
    NodeSystemStatsDto,
    NodeVersionsDto,
    ServiceEventDto,
    TorrentBlockerEventDto,
    TorrentBlockerReportDto,
    UserDto,
    UserEventDto,
    UserHwidDeviceEventDto,
    UserTrafficDto,
    WebhookNodeConfigProfileDto,
    WebhookPayloadDto,
)
__all__ = [
    # Auth models
    "GetStatusResponseDto",
    "LoginRequestDto",
    "LoginResponseDto",
    "RegisterRequestDto",
    "RegisterResponseDto",
    "StatusResponseDto",  # Legacy alias
    "TelegramCallbackRequestDto",
    "TelegramCallbackResponseDto",
    "LoginTelegramRequestDto",  # Legacy alias
    "OAuth2AuthorizeRequestDto",
    "OAuth2AuthorizeResponseDto",
    "OAuth2CallbackRequestDto",
    "OAuth2CallbackResponseDto",
    "VerifyPasskeyAuthenticationRequestDto",
    "VerifyPasskeyAuthenticationResponseDto",
    "GetPasskeyAuthenticationOptionsResponseDto",
    "BrandingSettings",
    # Nodes models
    "CreateNodeRequestDto",
    "CreateNodeResponseDto",
    "DeleteNodeResponseDto",
    "DisableNodeResponseDto",
    "EnableNodeResponseDto",
    "ExcludedInbounds",
    "GetAllNodesResponseDto",
    "GetAllNodesTagsResponseDto",
    "GetOneNodeResponseDto",
    "NodeResponseDto",
    "NodesResponseDto",  # Legacy alias
    "ReorderNodeRequestDto",
    "ReorderNodeResponseDto",
    "RestartAllNodesResponseDto",
    "RestartNodeResponseDto",
    "UpdateNodeRequestDto",
    "UpdateNodeResponseDto",
    "NodeConfigProfileDto",
    "NodeConfigProfileRequestDto",
    "RestartAllNodesRequestDto",  # Legacy alias
    "RestartAllNodesRequestBodyDto",
    "RestartNodeRequestBodyDto",
    "ResetNodeTrafficRequestDto",
    "ResetNodeTrafficResponseDto",
    "ProfileModificationRequestDto",
    "ProfileModificationResponseDto",
    "NodeBulkActionType",
    "NodesBulkActionsRequestDto",
    "NodesBulkActionsResponseDto",
    "NodesUpdateFieldsDto",
    "BulkNodesUpdateRequestDto",
    "BulkNodesUpdateResponseDto",
    # Hosts models
    "CreateHostRequestDto",
    "CreateHostResponseDto",
    "DeleteHostResponseDto",
    "GetAllHostsResponseDto",
    "GetOneHostResponseDto",
    "HostResponseDto",
    "HostsResponseDto",  # Legacy alias
    "ReorderHostRequestDto",
    "ReorderHostResponseDto",
    "UpdateHostRequestDto",
    "UpdateHostResponseDto",
    "GetAllHostTagsResponseDto",
    "CreateHostInboundData",
    "HostInboundData",
    "ReorderHostItem",
    # Inbounds models
    "AllInboundsData",
    "FullInboundResponseDto",
    "FullInboundStatistic",
    "FullInboundsResponseDto",
    "GetAllInboundsResponseDto",
    "GetFullInboundsResponseDto",
    "GetInboundsResponseDto",
    "InboundResponseDto",
    "InboundsResponseDto",  # Legacy alias
    "GetInternalSquadAccessibleNodesResponseDto",
    "InboundsByProfileData",
    # Keygen models
    "GetPubKeyResponseDto",
    "PubKeyResponseDto",  # Legacy alias
    # Subscription models
    "GetAllSubscriptionsResponseDto",
    "GetSubscriptionByUsernameResponseDto",
    "GetSubscriptionByShortUUIDResponseDto",
    "GetSubscriptionByUserIdResponseDto",
    "GetSubscriptionInfoResponseDto",
    "SubscriptionInfoResponseDto",  # Legacy alias
    "UserSubscription",
    "GetRawSubscriptionByShortUuidResponseDto",
    "RawSettings",
    "GetConnectionKeysByUuidResponseDto",
    # Subscription settings models
    "GetSubscriptionSettingsResponseDto",
    "SubscriptionSettingsResponseDto",
    "UpdateSubscriptionSettingsRequestDto",
    "SubscriptionType",
    "CustomRemarksDto",
    "HwidSettingsDto",
    # Backward compatibility aliases
    "CustomRemarks",
    "HwidSettings",
    "UpdateSubscriptionSettingsResponseDto",
    "ResponseModificationEncryption",
    "ResponseModificationHeader",
    "ResponseModifications",
    "ResponseRule",
    "ResponseRuleCondition",
    "ResponseRules",
    "ResponseRulesSettings",
    # Subscription template models
    "GetTemplateResponseDto",
    "TemplateResponseDto",
    "UpdateTemplateRequestDto",
    "UpdateTemplateResponseDto",
    "CreateSubscriptionTemplateRequestDto",
    "CreateSubscriptionTemplateResponseDto",
    "DeleteSubscriptionTemplateResponseDto",
    "GetTemplatesResponseDto",
    "ReorderTemplateItem",
    "ReorderSubscriptionTemplatesRequestDto",
    "ReorderSubscriptionTemplatesResponseDto",
    "TemplateInfoDto",
    # System models
    "BandwidthStatistic",
    "BandwidthStatisticResponseDto",
    "CPUStatistic",
    "GetBandwidthStatsResponseDto",
    "GetNodesStatisticsResponseDto",
    "GetRemnawaveHealthResponseDto",
    "GetStatsResponseDto",
    "MemoryStatistic",
    "NodeStatistic",
    "NodesStatisticResponseDto",
    "OnlineStatistic",
    "StatisticResponseDto",
    "StatusCounts",
    "UsersStatistic",
    "GetNodesMetricsResponseDto",
    "GetX25519KeyPairResponseDto",
    "X25519KeyPair",
    "DebugSrrMatcherRequestDto",
    "DebugSrrMatcherResponseDto",
    "EncryptHappCryptoLinkRequestDto",
    "EncryptHappCryptoLinkResponseDto",
    "GetMetadataResponseDto",
    "GetRecapResponseDto",
    "RecapThisMonth",
    "RecapTotal",
    "GetConfigurationResponseDto",
    "ConfigurationNotifications",
    "ConfigurationService",
    "ConfigurationMisc",
    "GetStatsDigestResponseDto",
    "StatsDigestUsers",
    "StatsDigestTraffic",
    "StatsDigestHwidDevices",
    "GetHttpStatsResponseDto",
    "HttpStatsRoute",
    # HWID models
    "CreateHWIDUser",  # Legacy alias
    "CreateUserHwidDeviceRequestDto",
    "CreateUserHwidDeviceResponseDto",
    "DeleteUserHwidDeviceRequestDto",
    "DeleteUserHwidDeviceResponseDto",
    "GetUserHwidDevicesResponseDto",
    "HWIDDeleteRequest",  # Legacy alias
    "HWIDUserResponseDto",  # Legacy alias
    "HWIDUserResponseDtoList",  # Legacy alias
    "GetHwidStatisticsResponseDto",
    "DeleteUserAllHwidDeviceRequestDto",
    "GetTopUsersByHwidDevicesResponseDto",
    "TopUserByHwidDevicesDto",
    "TopUsersByHwidDevicesData",
    # Bandwidth stats models
    "GetNodeUserUsageByRangeResponseDto",
    "GetNodesRealtimeUsageResponseDto",
    "GetNodesUsageByRangeResponseDto",
    "GetUserUsageByRangeResponseDto",
    "NodeRealtimeUsageResponseDto",
    "NodeUsageResponseDto",
    "NodesRealtimeUsageResponseDto",  # Legacy alias
    "NodesUsageResponseDto",  # Legacy alias
    "GetStatsNodesRealtimeUsageResponseDto",
    "GetStatsNodesUsageResponseDto",
    "GetStatsNodesUsersUsageRequestDto",
    "GetStatsNodesUsersUsageResponseDto",
    "GetStatsNodeUsersUsageResponseDto",
    "GetStatsUserUsageResponseDto",
    "NodeRealtimeUsageItem",
    "TopNodeItem",
    "TopUserItem",
    "NodeSeriesItem",
    "StatsNodesUsageData",
    "StatsNodeUsersUsageData",
    "StatsUserUsageData",
    "GetInternalSquadUserUsageResponseDto",
    "SquadUserUsageDay",
    "SquadUserUsageNode",
    "GetNodesUsageRequestDto",
    "GetNodesUsageResponseDto",
    "NodeUsageEntry",
    "NodeUsageUser",
    # API Tokens models
    "CreateApiTokenRequestDto",
    "CreateApiTokenResponseDto",
    "DeleteApiTokenResponseDto",
    "FindAllApiTokensResponseDto",
    "GetApiTokenScopesResponseDto",
    # Host bulk actions models
    "BulkDeleteHostsResponseDto",
    "BulkDisableHostsResponseDto",
    "BulkEnableHostsResponseDto",
    "UpdateManyHostsRequestDto",
    "UpdateManyHostsResponseDto",
    # Users models
    "CreateUserRequestDto",
    "UpdateUserRequestDto",
    "RevokeUserRequestDto",
    "ResolveUserRequestBodyDto",
    "ResolveUserResponseDto",
    "CreateUserResponseDto",
    "UpdateUserResponseDto",
    "GetUserByShortUuidResponseDto",
    "GetUserByUsernameResponseDto",
    "GetUserByIdResponseDto",
    "DisableUserResponseDto",
    "EnableUserResponseDto",
    "ResetUserTrafficResponseDto",
    "RevokeUserSubscriptionResponseDto",
    "ActivateAllInboundsResponseDto",
    "GetAllUsersResponseDto",
    "GetUsersStreamResponseDto",
    "GetAllTagsResponseDto",
    "GetUserSubscriptionRequestHistoryResponseDto",
    "ExtendUserRequestDto",
    "ExtendUserResponseDto",
    "DeleteUserResponseDto",
    "UserResponseDto",
    "UsersResponseDto",
    "TagsResponseDto",
    "SubscriptionRequestsResponseData",
    "UserTrafficDto",
    "ActiveInternalSquadDto",
    "SubscriptionRequestRecord",
    "HappCrypto",
    "UserActiveInboundsDto",
    "UserLastConnectedNodeDto",
    "GetSubscriptionRequestsResponseDto",
    # Users bulk actions models
    "BulkAllExtendExpirationDateRequestDto",
    "BulkAllExtendExpirationDateResponseDto",
    "BulkAllResetTrafficUsersResponseDto",
    "BulkAllUpdateUsersRequestDto",
    "BulkAllUpdateUsersResponseDto",
    "BulkDeleteUsersByStatusRequestDto",
    "BulkDeleteUsersByStatusResponseDto",
    "BulkDeleteUsersRequestDto",
    "BulkDeleteUsersResponseDto",
    "BulkEventResponseData",
    "BulkExtendExpirationDateRequestDto",
    "BulkExtendExpirationDateResponseDto",
    "BulkResetTrafficUsersRequestDto",
    "BulkResetTrafficUsersResponseDto",
    "BulkResponseData",
    "BulkResponseDto",
    "BulkRevokeUsersSubscriptionRequestDto",
    "BulkRevokeUsersSubscriptionResponseDto",
    "BulkUpdateUsersInternalSquadsRequestDto",
    "BulkUpdateUsersRequestDto",
    "BulkUpdateUsersResponseDto",
    "BulkUpdateUsersSquadsRequestDto",
    "BulkUpdateUsersSquadsResponseDto",
    "TagStr",
    "UpdateUserFields",
    # Users stats models
    "UserUsageByRange",
    "UserUsageByRangeResponseDto",
    # Config profiles models
    "ConfigProfileDto",
    "CreateConfigProfileRequestDto",
    "CreateConfigProfileResponseDto",
    "DeleteConfigProfileResponseDto",
    "GetAllConfigProfilesResponseDto",
    "GetAllConfigProfileInboundsResponseDto",
    "GetConfigProfileByUuidResponseDto",
    "GetInboundsByProfileUuidResponseDto",
    "InboundDto",
    "NodesProfileDto",
    "ReorderConfigProfileItem",
    "ReorderConfigProfilesRequestDto",
    "ReorderConfigProfilesResponseDto",
    "UpdateConfigProfileRequestDto",
    "UpdateConfigProfileResponseDto",
    "GetAllConfigProfilesResponsePaginated",
    # Infra billing models
    "CreateInfraBillingHistoryRecordRequestDto",
    "CreateInfraBillingHistoryRecordResponseDto",
    "CreateInfraBillingNodeRequestDto",
    "CreateInfraBillingNodeResponseDto",
    "CreateInfraProviderRequestDto",
    "CreateInfraProviderResponseDto",
    "DeleteInfraBillingHistoryRecordByUuidResponseDto",
    "DeleteInfraBillingNodeByUuidResponseDto",  # ПЕРЕИМЕНОВАНА (было DeleteInfraBillingNodeResponseDto)
    "DeleteInfraProviderByUuidResponseDto",  # ПЕРЕИМЕНОВАНА (было DeleteInfraProviderResponseDto)
    "GetInfraBillingHistoryRecordsResponseDto",  # ПЕРЕИМЕНОВАНА (было GetAllInfraBillingHistoryResponseDto)
    "GetInfraBillingNodesResponseDto",  # ПЕРЕИМЕНОВАНА (было GetAllInfraBillingNodesResponseDto)
    "GetInfraProvidersResponseDto",  # ПЕРЕИМЕНОВАНА (было GetAllInfraProvidersResponseDto)
    "GetInfraBillingHistoryByUuidResponseDto",
    "GetInfraBillingNodeByUuidResponseDto",
    "GetInfraProviderByUuidResponseDto",
    "InfraBillingHistoryDto",
    "InfraBillingNodeDto",
    "InfraProviderDto",
    "NodeDto",
    "UpdateInfraBillingNodeRequestDto",
    "UpdateInfraBillingNodeResponseDto",
    "UpdateInfraProviderRequestDto",
    "UpdateInfraProviderResponseDto",
    "DeleteInfraBillingNodeResponseDto",  # LEGACY
    "DeleteInfraProviderResponseDto",  # LEGACY
    "GetAllInfraBillingHistoryResponseDto",  # LEGACY
    "GetAllInfraBillingNodesResponseDto",  # LEGACY
    "GetAllInfraProvidersResponseDto",  # LEGACY
    # Internal squads models
    "AddUsersToInternalSquadRequestDto",
    "AddUsersToInternalSquadResponseDto",
    "CreateInternalSquadRequestDto",
    "CreateInternalSquadResponseDto",
    "DeleteInternalSquadResponseDto",
    "DeleteUsersFromInternalSquadRequestDto",
    "DeleteUsersFromInternalSquadResponseDto",
    "GetAllInternalSquadsResponseDto",
    "GetInternalSquadByUuidResponseDto",
    "InternalSquadDto",
    "ReorderInternalSquadItem",
    "ReorderInternalSquadsRequestDto",
    "ReorderInternalSquadsResponseDto",
    "UpdateInternalSquadRequestDto",
    "UpdateInternalSquadResponseDto",
    "GetInternalSquadAccessibleNodesResponseDto",
    "GetInternalSquadUsageResponseDto",
    "InternalSquadUsageUser",
    "AddManyUsersToInternalSquadRequestDto",
    "AddManyUsersToInternalSquadResponseDto",
    "DeleteManyUsersFromInternalSquadRequestDto",
    "DeleteManyUsersFromInternalSquadResponseDto",
    # Nodes usage history models
    "GetNodeUserUsageByRangeResponseDto",
    "GetNodesUsageByRangeResponseDto",
    "GetUserAccessibleNodesResponseDto",
    "NodeInfoDto",
    "NodeUsageDto",
    "UserUsageDto",
    # Subscription request history models
    "GetAllSubscriptionRequestHistoryResponseDto",
    "GetSubscriptionRequestHistoryStatsResponseDto",
    "SubscriptionRequestHistoryRecord",
    "SubscriptionRequestHistoryData",
    "AppStatItem",
    "HourlyRequestStat",
    "SubscriptionRequestHistoryStatsData",
    # Webhook models
    # USER
    "LastConnectedNodeDto",
    "InternalSquadDto",
    "BaseUserDto",
    "UserDto",
    "UserEventDto",
    "UserTrafficDto",
    # HWID DEVICES
    "HwidUserDeviceDto",
    "UserHwidDeviceEventDto",
    # SERVICE EVENTS
    "LoginAttemptDto",
    "ServiceEventDto",
    # NODE ENTITIES
    "ConfigProfileInboundDto",
    "InfraProviderDto",
    "NodeDto",
    "WebhookNodeConfigProfileDto",
    "NodeEventDto",
    # ERROR EVENTS
    "CustomErrorEventDto",
    # CRM EVENTS
    "CrmEventDto",
    # TORRENT BLOCKER EVENTS
    "TorrentBlockerEventDto",
    "TorrentBlockerReportDto",
    # NODE SYSTEM/VERSIONS
    "NodeSystemDto",
    "NodeSystemInfoDto",
    "NodeSystemStatsDto",
    "NodeSystemInterfaceDto",
    "NodeVersionsDto",
    # WEBHOOK PAYLOAD
    "WebhookPayloadDto",
    # Passkeys models
    "DeletePasskeyRequestDto",
    "DeletePasskeyResponseDto",
    "GetAllPasskeysResponseDto",
    "GetPasskeyRegistrationOptionsResponseDto",
    "PasskeyDto",
    "UpdatePasskeyRequestDto",
    "UpdatePasskeyResponseDto",
    "VerifyPasskeyRegistrationRequestDto",
    "VerifyPasskeyRegistrationResponseDto",
    # External squads models
    "AddUsersToExternalSquadResponseDto",
    "CreateExternalSquadRequestDto",
    "CreateExternalSquadResponseDto",
    "DeleteExternalSquadResponseDto",
    "ExternalSquadDto",
    "ExternalSquadInfoDto",
    "ExternalSquadSubscriptionSettingsDto",
    "ExternalSquadTemplateDto",
    "GetExternalSquadByUuidResponseDto",
    "GetExternalSquadsResponseDto",
    "RemoveUsersFromExternalSquadResponseDto",
    "ReorderExternalSquadItem",
    "ReorderExternalSquadsRequestDto",
    "ReorderExternalSquadsResponseDto",
    "TemplateType",
    "UpdateExternalSquadRequestDto",
    "UpdateExternalSquadResponseDto",
    # Snippets models
    "CreateSnippetRequestDto",
    "CreateSnippetResponseDto",
    "DeleteSnippetRequestDto",
    "DeleteSnippetResponseDto",
    "GetSnippetsResponseDto",
    "SnippetItem",
    "SnippetsData",
    "UpdateSnippetRequestDto",
    "UpdateSnippetResponseDto",
    # Remnawave settings models
    "BrandingSettings",
    "GetRemnawaveSettingsResponseDto",
    "GenericOAuth2Settings",
    "GitHubOAuth2Settings",
    "KeycloakOAuth2Settings",
    "OAuth2Settings",
    "PasskeySettings",
    "PasswordSettings",
    "PocketIdOAuth2Settings",
    "RemnawaveSettingsData",
    "TelegramAuthSettings",
    "UpdateRemnawaveSettingsRequestDto",
    "UpdateRemnawaveSettingsResponseDto",
    "YandexOAuth2Settings",
    # Subscription page config models
    "CloneSubscriptionPageConfigRequestDto",
    "CloneSubscriptionPageConfigResponseDto",
    "CreateSubscriptionPageConfigRequestDto",
    "CreateSubscriptionPageConfigResponseDto",
    "DeleteSubscriptionPageConfigResponseDto",
    "GetSubscriptionPageConfigResponseDto",
    "GetSubscriptionPageConfigsResponseDto",
    "GetSubpageConfigByShortUuidRequestBodyDto",
    "GetSubpageConfigByShortUuidResponseDto",
    "SubpageConfigData",
    "ReorderSubscriptionPageConfigItem",
    "ReorderSubscriptionPageConfigsRequestDto",
    "ReorderSubscriptionPageConfigsResponseDto",
    "SubscriptionPageConfigDto",
    "UpdateSubscriptionPageConfigRequestDto",
    "UpdateSubscriptionPageConfigResponseDto",
    # Connections models
    "DropConnectionsRequestDto",
    "DropByUserIds",
    "DropByIpAddresses",
    "TargetAllNodes",
    "TargetSpecificNodes",
    "DropConnectionsResponseDto",
    "ConnectionsJobData",
    "ConnectionsByNodeResponseDto",
    "ConnectionsByUserResponseDto",
    "ConnectionIp",
    "ConnectionsByNodeUser",
    "ConnectionsByNodeResult",
    "ConnectionsByNodeResultResponseDto",
    "ConnectionsProgress",
    "ConnectionsByUserNode",
    "ConnectionsByUserResult",
    "ConnectionsByUserResultResponseDto",
    # Metadata models
    "MetadataResponseDto",
    "GetUserMetadataResponseDto",
    "UpsertUserMetadataRequestBodyDto",
    "UpsertUserMetadataResponseDto",
    "GetNodeMetadataResponseDto",
    "UpsertNodeMetadataRequestBodyDto",
    "UpsertNodeMetadataResponseDto",
    # Node plugins models
    "GetTorrentBlockerReportsResponseDto",
    "GetTorrentBlockerReportsStatsResponseDto",
    "TruncateTorrentBlockerReportsResponseDto",
    "GetNodePluginsResponseDto",
    "GetNodePluginResponseDto",
    "UpdateNodePluginRequestDto",
    "UpdateNodePluginResponseDto",
    "DeleteNodePluginResponseDto",
    "CreateNodePluginRequestDto",
    "CreateNodePluginResponseDto",
    "ReorderNodePluginItem",
    "ReorderNodePluginsRequestDto",
    "ReorderNodePluginsResponseDto",
    "CloneNodePluginRequestDto",
    "CloneNodePluginResponseDto",
    "PluginExecutorRequestDto",
    "PluginExecutorResponseDto",
    "BlockIpsCommandDto",
    "UnblockIpsCommandDto",
    "RecreateTablesCommandDto",
    "BlockIpItemDto",
    "TorrentBlockerReportRecordDto",
    "NodePluginDto",
    "TargetAllNodesDto",
    "TargetSpecificNodesDto",
]
